{"name": "test3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <py_test.TestCase object at 0x000002F1837A0160>\n\n    @pytest.mark.run(order=1)\n    def test3(self):\n        print(\"第三条用例\")\n>       assert 1==2\nE       assert 1 == 2\n\nscripts\\py_test.py:27: AssertionError"}, "start": 1625558636780, "stop": 1625558636780, "uuid": "a309c4af-5aa4-42f4-9fea-f2ba3e5ef915", "historyId": "2ea28c94e79c486f677fb49846eeb278", "testCaseId": "422553892c11965e6020ed5ffafd579f", "fullName": "scripts.py_test.TestCase#test3", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "py_test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "LAPTOP-TNIA2CIB"}, {"name": "thread", "value": "16228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.py_test"}]}